import '../models/models.dart';

class DummyData {
  static final CaptainDetails dummyCaptain = CaptainDetails(
    user: AppUser(
      id: 'cap_1',
      name: 'سيد محمد ولد بونا',
      phone: '+22233333333',
      rating: 4.9,
      tripsCount: 152,
      type: UserType.captain,
      avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Sidi',
    ),
    vehicle: Vehicle(
      brand: 'تويوتا',
      model: 'كورولا',
      year: 2018,
      color: 'رمادي ميتاليك',
      plate: '4567 AA 00',
      seats: 4,
      type: VehicleType.economy,
    ),
    acceptanceRate: 94.0,
    cancellationRate: 2.5,
    documentsStatus: {
      'personal_photo': 'accepted',
      'national_id': 'accepted',
      'driver_license': 'accepted',
      'car_card': 'accepted',
      'car_photo': 'accepted',
      'car_insurance': 'accepted',
    },
  );

  static final List<Trip> dummyCaptainTrips = [
    Trip(
      id: 'trip_201',
      customerName: 'فاطمة منت اعل',
      customerPhone: '+22245555555',
      captainName: 'سيد محمد ولد بونا',
      captainPhone: '+22233333333',
      pickupLocation: 'تيارت',
      destinationLocation: 'سوق العاصمة',
      pickupLat: 18.1255,
      pickupLng: -15.9288,
      destLat: 18.0878,
      destLng: -15.9789,
      distance: 6.5,
      duration: 18,
      price: 200.0,
      paymentMethod: 'Masrvi',
      status: TripStatus.completed,
      carType: VehicleType.economy,
      isOpenRide: false,
      openRideTimeout: 45,
      date: '2026-07-10 12:30',
      netEarnings: 170.0,
      commission: 30.0,
    ),
    Trip(
      id: 'trip_202',
      customerName: 'النان ولد المختار',
      customerPhone: '+22246666666',
      captainName: 'سيد محمد ولد بونا',
      captainPhone: '+22233333333',
      pickupLocation: 'تفرغ زينة',
      destinationLocation: 'دار النعيم',
      pickupLat: 18.1065,
      pickupLng: -15.9664,
      destLat: 18.1098,
      destLng: -15.9087,
      distance: 8.9,
      duration: 25,
      price: 300.0,
      paymentMethod: 'نقداً',
      status: TripStatus.completed,
      carType: VehicleType.economy,
      isOpenRide: true,
      openRideTimeout: 30,
      date: '2026-07-10 09:15',
      netEarnings: 255.0,
      commission: 45.0,
    ),
  ];

  static final List<WalletTransaction> dummyCaptainTransactions = [
    WalletTransaction(
      id: 'tx_201',
      amount: 170.0,
      type: TransactionType.charge,
      title: 'أرباح رحلة #trip_201',
      date: '2026-07-10 12:48',
      isCredit: true,
    ),
    WalletTransaction(
      id: 'tx_202',
      amount: 30.0,
      type: TransactionType.commission,
      title: 'عمولة تطبيق الهدهد لرحلة #trip_201',
      date: '2026-07-10 12:48',
      isCredit: false,
    ),
    WalletTransaction(
      id: 'tx_203',
      amount: 500.0,
      type: TransactionType.withdraw,
      title: 'سحب رصيد إلى حساب Bankily',
      date: '2026-07-09 20:00',
      isCredit: false,
    ),
    WalletTransaction(
      id: 'tx_204',
      amount: 100.0,
      type: TransactionType.reward,
      title: 'مكافأة الكابتن المتميز الأسبوعية',
      date: '2026-07-06 00:00',
      isCredit: true,
    ),
  ];

  static final List<Message> dummyMessages = [
    Message(
      id: 'msg_1',
      senderId: 'cap_1',
      senderName: 'سيد محمد ولد بونا',
      content: 'السلام عليكم، أنا في الطريق إليك.',
      time: '12:32 م',
      isMe: true,
    ),
    Message(
      id: 'msg_2',
      senderId: 'cust_1',
      senderName: 'أحمد سالم ولد محمد',
      content: 'وعليكم السلام، ممتاز أنا في انتظارك عند البوابة.',
      time: '12:33 م',
      isMe: false,
    ),
    Message(
      id: 'msg_3',
      senderId: 'cap_1',
      senderName: 'سيد محمد ولد بونا',
      content: 'لقد وصلت للموقع تقريباً.',
      time: '12:38 م',
      isMe: true,
    ),
  ];
}
